# Generated by Django 5.1.4 on 2025-01-01 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskgroup'),
        ),
    ]
